// vue/src/App.vue
<script setup>
  import Language from './components/Language.vue';
</script>

<template>
  <header class="w-screen flex justify-center bg-[#27272A] py-4 px-0">
    <div class="py-[6px] px-5 bg-[#DADADA54] rounded-lg">
      <img src="./assets/logo.svg" alt="StackX">
    </div>
  </header>

  <section class="w-[791px] my-0 mx-auto mt-24 text-2xl text-center font-medium text-white font-sans">
    <p v-if="lang == 'português' ">Olá, meu nome é <strong>Keven Rodrigues Meirelles</strong> Lennon e eu sou Desenvolvedor Front-end,
      <strong>Tecnologias que tenho experiência:</strong>
    </p>
    
    <p v-if="lang == 'inglês' ">
      Hi, my name is <strong>Keven Rodrigues Meirelles</strong> Lennon and I'm a Front-end Developer, 
      <strong>Technologies I have experience with:</strong>      
    </p>
    
    <p v-if="lang == 'espanhol' ">
      Hola, mi nombre es <strong>Keven Rodrigues Meirelles</strong> Lennon y soy desarrollador front-end, 
      <strong>tecnologías con las que tengo experiencia:</strong>      
    </p>
  </section>

  <div class="my-0 mx-auto mt-16 py-[22px] px-14 pr-0 bg-[#27272A] border-[1px] border-[#9D4B00] rounded-lg">
    <ul class="gap-[100px] columns-3 list-disc">
      <li v-for="(item) in techs" class="font-sans font-medium text-lg text-[#EDEDED]">
        {{ item }}
      </li>
    </ul>
  </div>

  <footer class="flex justify-center flex-wrap gap-[50px] w-screen mt-auto pb-7">
    <Language titulo="Português" icone="Português" :click="() => updateLang('português')" />
    <Language titulo="Inglês" icone="Inglês" :click="() => updateLang('inglês')" />
    <Language titulo="Espanhol" icone="Espanhol" :click="() => updateLang('espanhol')" />
  </footer>
</template>

<script>
export default {
  data() {
    return {
      techs: ["JavaScript", "React", "Vue Js", "Tailwind CSS", "Styled Components", "Saas", "Node", "TypeScript", "Angular", "Java"],
      lang: 'português'
    };
  },
  methods: {
    updateLang(value){
      this.lang = value;
    }
  },
  components: { Language }
}
</script>

// angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.sass']
})
export class AppComponent {
  techs = [
    "JavaScript",
    "React",
    "Vue Js",
    "Tailwind CSS",
    "Styled Components",
    "Sass",
    "Node",
    "Typescript",
    "Angular",
    "Java",
  ];

  lang = 'português'

  changeLang(value: string){
    this.lang = value;
  }
}

<div class="container">
  <header>
    <div class="logo">
      <img src="./assets/logo.svg" alt="StackX">
    </div>
  </header>
  
  <section>
    <p *ngIf="lang == 'português'">
      Olá, meu nome é <strong>Keven Rodrigues Meirelles</strong> Lennon e eu sou Desenvolvedor Front-end,
      <strong>Tecnologias que tenho experiência:</strong>
    </p>
  
    <p *ngIf="lang == 'inglês'">
      Hi, my name is <strong>Keven Rodrigues Meirelles</strong> Lennon and I'm a Front-end Developer,
      <strong>Technologies I have experience with:</strong>
    </p>
  
    <p *ngIf="lang == 'espanhol'">
      Hola, mi nombre es <strong>Keven Rodrigues Meirelles</strong> Lennon y soy desarrollador front-end,
      <strong>tecnologías con las que tengo experiencia:</strong>
    </p>
  </section>
  
  <div class="technologies">
    <ul>
      <li *ngFor="let tech of techs;">{{ tech }}</li>
    </ul>
  </div>

  <footer>
    <app-language titulo="Português" icone="português" (click)="changeLang('português')" ></app-language>
    <app-language titulo="Inglês" icone="inglês" (click)="changeLang('inglês')"></app-language>
    <app-language titulo="Espanhol" icone="espanhol" (click)="changeLang('espanhol')"></app-language>
  </footer>
</div>
